package com.zlx.user.dal.mapper;

import com.zlx.user.dal.model.CourseDO;
import com.zlx.user.dal.model.CourseDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int countByExample(CourseDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int deleteByExample(CourseDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    List<CourseDO> selectByExample(CourseDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    CourseDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") CourseDO record, @Param("example") CourseDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int updateByExample(@Param("record") CourseDO record, @Param("example") CourseDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated Fri Aug 03 17:28:20 CST 2018
     */
    int updateByPrimaryKey(CourseDO record);
}